baseURL = "http://LucyDada.com/"
title = "Lucy Dada - the book series"

tags = ["book", "novel", "author", "romantic", "sexy", "book series", "lucy dada", "blog"]
languageCode = "en-GB"

config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Lucy Dada"
    author = "Lucy Dada"
    description = "Lucy Dada's only commitment is to romantic vagabondage. She writes smutty listicles for a digital media and broadcasting corporation and is venturing into self publishing as a side hustle."
    logoBig = "lucy-dada.jpg"
    logoSmall = "lucy-dada.jpg"
    opengraphImage = "lucy-dada.jpg"
    favicon = "favicon.ico"
    twitter = "LucyDada"
    linkedin = ""
    github = ""
    facebook = "LucyDada"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true
	form_post_url = "https://script.google.com/macros/s/AKfycbzKBozQPwbIH2i7HmdVHRg_XvvZga7G1IZ6M_vK/exec"


[[menu.main]]
    name = "Book I"
    url  = "/#book"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 5
[[menu.main]]
    name = "Extras"
    url  = "/#extras"
    weight = 7

