baseURL = "http://LucyDada.com/"
title = "Lucy Dada - the book series"

tags = ["book", "novel", "author", "romantic", "sexy", "book series", "lucy dada", "blog"]
languageCode = "en-GB"

config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-125141349-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Lucy Dada"
    author = "Lucy Dada"
    description = "Lucy Dada's only commitment is to romantic vagabondage. Frustrated with her job at a digital media and broadcasting corporation, she's self-publishing the unfiltered version of her experiences on the side."
    logoBig = "images/lucy-dada.jpg"
    logoSmall = "images/lucy-dada.jpg"
    opengraphImage = "images/lucy-dada-book-1-passive-restraint.jpg"
    favicon = "favicon.ico"
    twitter = ""
    linkedin = ""
    github = ""
    facebook = "Lucy-Dada-256508861852673"
    fediverse = "https://writing.exchange/@LucyDada"
    goodreads = "https://www.goodreads.com/author/show/18382272.Lucy_Dada"
	  link_ebook = "http://a-fwd.to/5l4YDJw"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true
	  form_post_url = "https://script.google.com/macros/s/AKfycbzKBozQPwbIH2i7HmdVHRg_XvvZga7G1IZ6M_vK/exec"


[[menu.main]]
    name = "Book I"
    url  = "/#book"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 5
[[menu.main]]
    name = "Extras"
    url  = "/#extras"
    weight = 7

